language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.1-0-dev
  - sudo apt-get install -y libgtk2.0-dev libpango1-dev libcairo2-dev libfontconfig1-dev

script:
  - make -j4
