language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -qq install -y lua-dev
  - sudo apt-get -qq install -y gtk+-2.0-dev

script:
  - make -j4
